export const LIST_ERRORS_HTTP = [
  { name: 'Continue', statusCode: 100 },
  { name: 'Switching Protocols', statusCode: 101 },
  { name: 'Processing', statusCode: 102 },
  { name: 'Early Hints', statusCode: 103 },
  { name: 'OK', statusCode: 200 },
  { name: 'Created', statusCode: 201 },
  { name: 'Accepted', statusCode: 202 },
  { name: 'Non-Authoritative Information', statusCode: 203 },
  { name: 'No Content', statusCode: 204 },
  { name: 'Reset Content', statusCode: 205 },
  { name: 'Partial Content', statusCode: 206 },
  { name: 'Multi-Status', statusCode: 207 },
  { name: 'Already Reported', statusCode: 208 },
  { name: 'IM Used', statusCode: 226 },
  { name: 'Multiple Choices', statusCode: 300 },
  { name: 'Moved Permanently', statusCode: 301 },
  { name: 'Found', statusCode: 302 },
  { name: 'See Other', statusCode: 303 },
  { name: 'Not Modified', statusCode: 304 },
  { name: 'Use Proxy', statusCode: 305 },
  { name: 'Temporary Redirect', statusCode: 307 },
  { name: 'Permanent Redirect', statusCode: 308 },
  { name: 'Bad Request', statusCode: 400 },
  { name: 'Unauthorized', statusCode: 401 },
  { name: 'Payment Required', statusCode: 402 },
  { name: 'Forbidden', statusCode: 403 },
  { name: 'Not Found', statusCode: 404 },
  { name: 'Method Not Allowed', statusCode: 405 },
  { name: 'Not Acceptable', statusCode: 406 },
  { name: 'Proxy Authentication Required', statusCode: 407 },
  { name: 'Request Timeout', statusCode: 408 },
  { name: 'Conflict', statusCode: 409 },
  { name: 'Gone', statusCode: 410 },
  { name: 'Length Required', statusCode: 411 },
  { name: 'Precondition Failed', statusCode: 412 },
  { name: 'Payload Too Large', statusCode: 413 },
  { name: 'URI Too Long', statusCode: 414 },
  { name: 'Unsupported Media Type', statusCode: 415 },
  { name: 'Range Not Satisfiable', statusCode: 416 },
  { name: 'Expectation Failed', statusCode: 417 },
  { name: "I'm a teapot", statusCode: 418 },
  { name: 'Misdirected Request', statusCode: 421 },
  { name: 'Unprocessable Entity', statusCode: 422 },
  { name: 'Locked', statusCode: 423 },
  { name: 'Failed Dependency', statusCode: 424 },
  { name: 'Too Early', statusCode: 425 },
  { name: 'Upgrade Required', statusCode: 426 },
  { name: 'Precondition Required', statusCode: 428 },
  { name: 'Too Many Requests', statusCode: 429 },
  { name: 'Request Header Fields Too Large', statusCode: 431 },
  { name: 'Unavailable For Legal Reasons', statusCode: 451 },
  { name: 'Internal Server Error', statusCode: 500 },
  { name: 'Not Implemented', statusCode: 501 },
  { name: 'Bad Gateway', statusCode: 502 },
  { name: 'Service Unavailable', statusCode: 503 },
  { name: 'Gateway Timeout', statusCode: 504 },
  { name: 'Variant Also Negotiates', statusCode: 506 },
  { name: 'Insufficient Storage', statusCode: 507 },
  { name: 'Loop Detected', statusCode: 508 },
  { name: 'Not Extended', statusCode: 510 },
  { name: 'Network Authentication Required', statusCode: 511 },
  { name: 'Web Server Is Down', statusCode: 521 },
  { name: 'Connection Timed Out', statusCode: 522 },
  { name: 'Origin Is Unreachable', statusCode: 523 },
  { name: 'SSL Handshake Failed', statusCode: 525 },
  { name: 'Site is frozen', statusCode: 530 },
  { name: 'Network Timeout', statusCode: 599 }
];
